---
title: "work"
author: "Keiryn Hart, 300428418"
date: "20/08/2020"
output: html_document
---

# Does this not just do exactly the same thing as the initial clean - Sort the years and filter to be assault, if we use the file outputted from there this almost becomes obselete besides the NA checking and sorting??


```{r}
victims <- read.csv("/Users/keirynhart/Documents/Uni/Data 301/DATA301-Group-Project/Data/Victimizations_time_and_place (partly filtered).csv", header = TRUE)

```


```{r}
library(tidyverse)
library(lubridate)

victims <- victims %>% unite(date,c("day","month","year"),sep="/")

assault <- victims %>% filter(ANZSOC.Group == c("Serious Assault Not Resulting in Injury", "Non-Aggravated Sexual Assault", "Serious Assault Resulting in Injury", "Common Assault", "Aggravated Sexual Assault"))


unique(victims$ANZSOC.Group)
sum(is.na(assault))
nrow(assault)

assault$X <- NULL
head(assault)

write.csv(assault, "/Users/keirynhart/Documents/Uni/Data 301/DATA301-Group-Project/Data/Victimisations_time_and_place (cleaned).csv")
```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```


```{r}

```
